services:
  postgres:
    image: postgres:18
    container_name: habitrouter-postgres
    environment:
      POSTGRES_DB: habitrouter_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"